objects/copado__Deployment_Flow__c.object
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Back_Promotion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the promotion is from a higher environment to a lower environment in the deployment flow.</description>
        <inlineHelpText>Select this checkbox if you are promoting from a higher to a lower environment in the pipeline.</inlineHelpText>
        <label>Is Back-Promotion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a project linked to an active pipeline.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will provide the ability to deploy User Stories within a Release.</description>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MCContinuousDeliveryBatch.cls
public class MCContinuousDeliveryBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {
    private List<copado__Promotion__c> promotions;

    public MCContinuousDeliveryBatch(List<copado__Promotion__c> promotions) {
        this.promotions = promotions;
    }

    public Database.QueryLocator start(Database.BatchableContext batchContext) {
        String query = 'SELECT Id, copado__Back_Promotion__c, copado__Destination_Environment__c, copado__Source_Environment__c, copado__Release__c, copado__Release__r.copado__Project__c, copado__Release__r.copado__Project__r.copado__Deployment_Flow__c, copado__Project__c, copado__Project__r.copado__Deployment_Flow__c FROM copado__Promotion__c WHERE Id IN: promotions';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext batchContext, List<copado__Promotion__c> promotions) {
        for (copado__Promotion__c promotion : promotions) {
            List<copado.PromoteAction.Request> requests = new List<copado.PromoteAction.Request>();
            copado.PromoteAction.Request request = new copado.PromoteAction.Request();
            request.promotionId = promotion.Id;
            request.executePromotion = true;
            request.executeDeployment = true;
            request.deploymentDryRun = false;
            requests.add(request);
            copado.PromoteAction.promote(requests);
        }
    }

    public void finish(Database.BatchableContext batchContext) {
        // empty
    }
}